### ISSUE TITLE
Decimal Latitude fields - incorrect values

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/data-importer#4]
Decimal latitude fields > +/-90

   irn   |     lat      |     lon      
---------+--------------+--------------
 1233139 | -158.8336111 |  123.0666667
 2407969 |          117 |        124.1
 2407968 |          117 |        124.1
 2335249 | -90.63333333 |         12.7
 1233675 |  137.3847222 | -152.0333333
 1247798 |  137.3847222 | -152.0333333
 1247828 |  137.3847222 | -152.0333333
 1247874 |  137.3847222 | -152.0333333
 1233137 |  237.5769444 |  140.5333333
 1233135 |  237.5769444 |  140.5333333
 2235545 | -191.2666667 |  146.8166667
  671543 |         -178 |          174
  671541 |         -178 |          174
  671540 |         -178 |          174
  671542 |         -178 |          174
 1994152 | -90.08333333 | -34.81666667
 1233885 |  144.0833333 |        44.75
 3160750 | -129.4347222 | -71.33055556
 2252392 |  124.5833333 | -83.58333333
  622619 |          443 |          248
 2245912 |  130.0583333 |       114.65
 2252400 |  114.1666667 | -81.91666667
 1968299 |         -137 |          -19
 1968300 |         -137 |          -19
 3161402 | -153.5608333 |       29.935
 1887085 |  741.8833333 |  55.80833333
 2710187 |  98.76666667 |  15.36666667
 2710210 |        98.65 |        15.45
 2710209 |        98.65 |        15.45
 2710184 |        98.65 |        15.45
 2710183 |        98.65 |        15.45
 2710186 |        98.65 |        15.45
 2710185 |        98.65 |        15.45
 2710211 |        98.65 |        15.45
 2710212 |        98.65 |        15.45
 2711885 |        98.65 |        15.45
 2711886 |        98.65 |        15.45
 1918214 |  726.0833333 |  46.16666667
 1914599 |  724.1319444 |        44.25
 2404971 |       110.25 |  91.26666667
  671208 |       -333.4 |  21.76666667
 1962622 |  718.3166667 |          9.1
 2806145 | -97.15666667 |       39.175

**Comment by essvee** [comment]
Sounds like the incorrect values were a side effect of some work the DMs were doing to pull co-ordinates out of other eMU fields - should be a one off and Hillery's going to fix them asap.

**Comment by benscott** [comment]
Incorrect lat/lng fields will no longer break import process.
