### ISSUE TITLE
Incorrect decimal longitude fields

### ISSUE THREAD

**Issue by benscott** [NaturalHistoryMuseum/data-importer#5]
Longitude fields > +/-180

   irn   |     lat      |     lon      
---------+--------------+--------------
  658634 | -9.104166667 |  1116.452778
  658635 | -9.104166667 |  1116.452778
  671810 |          -76 |          186
  658636 | -9.104166667 |  1116.452778
 3182728 |  20.35878333 |  682.3333333
 3071659 |  20.35878333 |  682.3333333
 3071658 |  20.35878333 |  682.3333333
 3182729 |  20.35878333 |  682.3333333
 3182670 |  20.35878333 |  682.3333333
 3071660 |  20.35878333 |  682.3333333
 3072186 |  20.35736667 |  686.9166667
 3182594 |  20.35736667 |  686.9166667
 3071656 |  20.35736667 |  686.9166667
 3071655 |  20.35736667 |  686.9166667
 3182593 |  20.35736667 |  686.9166667
 3071651 |  20.35736667 |  686.9166667
  673617 | -7.466666667 |  1115.466667
  658637 | -9.104166667 |  1116.452778
 2217172 |  69.08333333 |  180.5833333
  679215 | -34.33333333 |        227.5
  622619 |          443 |          248
 1748279 |  8.616666667 | -255.2333333
 1250592 |  33.23333333 |  182.9166667
 1250610 |  33.23333333 |  182.9166667
 1250572 |  33.23333333 |  182.9166667
 2280887 | -9.766666667 |  1288.358333
 2280886 | -9.766666667 |  1288.358333
 2272037 | -9.766666667 |  1288.358333
 2331014 |  56.73333333 | -928.2666667

**Comment by essvee** [comment]
As #4

**Comment by benscott** [comment]
Using SOLR any incorrect lat/lng will no longer break import process.
